import PDFDocument from 'pdfkit'
import type { AuthorPersonaRow, StyleDescriptors, ThematicPreferences } from '@/types/database'

/**
 * Generate a PDF style report from an author persona.
 * Uses the PDFKit event-listener buffer-collection pattern (same as docx.ts).
 * Returns a Buffer suitable for use in a Next.js Response.
 */
export function buildVoiceReportPdf(persona: AuthorPersonaRow): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 60, size: 'letter' })
    const chunks: Buffer[] = []

    doc.on('data', (chunk: Buffer) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    // Title
    doc
      .fontSize(24)
      .font('Helvetica-Bold')
      .text('Author Voice Report', { align: 'center' })
    doc.moveDown(0.5)
    doc
      .fontSize(10)
      .font('Helvetica')
      .fillColor('#888888')
      .text(`Generated by StoryWriter — ${new Date().toLocaleDateString()}`, { align: 'center' })
    doc.fillColor('#000000')
    doc.moveDown(2)

    // Narrative editorial summary
    doc.fontSize(16).font('Helvetica-Bold').text('Voice Summary')
    doc.moveDown(0.5)
    doc
      .fontSize(12)
      .font('Helvetica')
      .text(persona.voice_description ?? 'Voice analysis not yet complete.', {
        align: 'left',
        lineGap: 4,
      })
    doc.moveDown(1.5)

    // AI Guidance Text
    if (persona.raw_guidance_text) {
      doc.fontSize(16).font('Helvetica-Bold').text('AI Generation Guidance')
      doc.moveDown(0.5)
      doc
        .fontSize(11)
        .font('Helvetica')
        .fillColor('#444444')
        .text(persona.raw_guidance_text, { lineGap: 3 })
      doc.fillColor('#000000')
      doc.moveDown(1.5)
    }

    // Style Descriptors
    if (persona.style_descriptors) {
      doc.addPage()
      doc.fontSize(16).font('Helvetica-Bold').text('Style Descriptors')
      doc.moveDown(0.5)
      const sd = persona.style_descriptors as StyleDescriptors
      const styleRows: [string, string][] = [
        ['Sentence Length', sd.sentence_length],
        ['Rhythm', sd.rhythm],
        ['Diction Level', sd.diction_level],
        ['POV Preference', sd.pov_preference],
      ]
      for (const [label, value] of styleRows) {
        doc.fontSize(13).font('Helvetica-Bold').text(label)
        doc.fontSize(11).font('Helvetica').text(value, { lineGap: 2 })
        doc.moveDown(0.8)
      }
    }

    // Thematic Preferences
    if (persona.thematic_preferences) {
      doc.moveDown(0.5)
      doc.fontSize(16).font('Helvetica-Bold').text('Thematic Preferences')
      doc.moveDown(0.5)
      const tp = persona.thematic_preferences as ThematicPreferences
      const themeRows: [string, string][] = [
        ['Tone', tp.tone],
        ['Pacing', tp.pacing],
        ['Dialogue Ratio', tp.dialogue_ratio],
        ['Dark / Light Themes', tp.dark_light_theme],
      ]
      for (const [label, value] of themeRows) {
        doc.fontSize(13).font('Helvetica-Bold').text(label)
        doc.fontSize(11).font('Helvetica').text(value, { lineGap: 2 })
        doc.moveDown(0.8)
      }
    }

    doc.end()
  })
}
